version: '3'

services:
  fastify-server:
    container_name: fastify-server
    build:
      context: .
      dockerfile: .apps/server/Dockerfile
    environment:
      - DATABASE_URL=mysql://root:mypassword@mysql-server:3306/mydb
    depends_on:
      mysql-server:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - local-net
    platform: linux/arm64

  mysql-server:
    container_name: mysql-server
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
      TZ: 'Asia/Tokyo'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 30
    ports:
      - "3306:3306"
    networks:
      - local-net
    platform: linux/arm64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8888:80
    environment:
      PMA_USER: testuser
      PMA_PASSWORD: mypassword
      PMA_HOST: mysql
    networks:
      - local-net

networks:
  local-net:
    driver: bridge