openapi: 3.0.0
info:
  title: Fastify API
  description: testing fastify swagger
  version: 0.0.0
components:
  schemas: {}
paths:
  /:
    get:
      responses:
        "200":
          description: Default Response
  /countries/:
    get:
      parameters:
        - schema:
            type: string
          in: query
          name: id
          required: false
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    japaneseName:
                      type: string
                    code:
                      type: string
                    flagUrl:
                      type: string
                  required:
                    - id
                    - name
                    - japaneseName
                    - code
                    - flagUrl
        "400":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "401":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "403":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
